name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Release type (default: node)"
        required: false
        default: node

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 🔖 Manual Release
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN}}
          release-type: ${{ github.event.inputs.release-type }}
